# Step 1: Data cleaning and preprocessing

In [1]:
#Import basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
sb.set()

In [2]:
#Import Cardio dataset
cardio = pd.read_csv('cardio_train.csv', sep=';')

#Read first few rows of dataset
cardio.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [3]:
#Find out more information about dataset
cardio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [4]:
#Create a copy of the dataset
cardio_clean = cardio.copy()

#Print the variable information to check
cardio_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [5]:
#Check for the presence of duplicate IDs
dupid_cardio_clean = cardio_clean[cardio_clean.duplicated("id", keep = False)]
print("Patient data with Duplicate IDs :", len(dupid_cardio_clean))

#Check for the presence of empty values in different variables
cardio_clean.isnull().sum()

Patient data with Duplicate IDs : 0

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [6]:
#Checking if 'id' is labelled sequentially and matches to the index
print("Count of values in index:", cardio_clean.index.max())

print("Count of values in 'id' variable:", cardio_clean['id'].max())

#Checking how many rows were labelled with the wrong 'id'
print("Number of missing id:", cardio_clean['id'].max()-cardio_clean.index.max())

Count of values in index: 69999
Count of values in 'id' variable: 99999
Number of missing id: 30000

In [7]:
#Change variable 'ap_hi' to 'bp_systolic' for easier reading
#Change variable 'ap_lo' to 'bp_diastolic' for easier reading
cardio_clean.rename(columns={'ap_hi': 'bp_systolic', 'ap_lo':'bp_diastolic'}, inplace=True)

#Check first few rows of dataset to see if new names of columns were transferred accordingly
cardio_clean.head()

,id,age,gender,height,weight,bp_systolic,bp_diastolic,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [8]:
#Checking if there's any irregularities in 'gender'
print("\nMinimum gender category:", cardio_clean['gender'].min())
print("Maximum gender category:", cardio_clean['gender'].max())

#Checking if there's any irregularities in 'height'
print("\nMinimum height in cm:", cardio_clean['height'].min())
print("Maximum height in cm:", cardio_clean['height'].max())

#Checking if there's any irregularities in 'weight'
print("\nMinimum weight category:", cardio_clean['weight'].min())
print("Maximum weight category:", cardio_clean['weight'].max())

#Checking if there's any irregularities in 'bp_systolic'
print("\nMinimum systolic blood pressure:", cardio_clean['bp_systolic'].min())
print("Maximum systolic blood pressure:", cardio_clean['bp_systolic'].max())

#Checking if there's any irregularities in 'bp_diastolic'
print("\nMinimum diastolic blood pressure:", cardio_clean['bp_diastolic'].min())
print("Maximum diastolic blood pressure:", cardio_clean['bp_diastolic'].max())

#Checking if there's any irregularities in 'cholesterol'
print("\nMinimum cholesterol category:", cardio_clean['cholesterol'].min())
print("Maximum cholesterol category:", cardio_clean['cholesterol'].max())

#Checking if there's any irregularities in 'gluc'
print("\nMinimum glucose category:", cardio_clean['gluc'].min())
print("Maximum glucose category:", cardio_clean['gluc'].max())

#Checking if there's any irregularities in 'smoke'
print("\nMinimum smoke category:", cardio_clean['smoke'].min())
print("Maximum smoke category:", cardio_clean['smoke'].max())

#Checking if there's any irregularities in 'alco'
print("\nMinimum alcohol category:", cardio_clean['alco'].min())
print("Maxmimum alcohol category:", cardio_clean['alco'].max())

#Checking if there's any irregularities in 'active'
print("\nMinimum active category:", cardio_clean['active'].min())
print("Maximum active category:", cardio_clean['active'].max())

#Checking if there's any irregularities in 'cardio'
print("\nMinimum cardio catgory:", cardio_clean['cardio'].min())
print("Maximum cardio category:", cardio_clean['cardio'].max())

Minimum gender category: 1
Maximum gender category: 2

Minimum height in cm: 55
Maximum height in cm: 250

Minimum weight category: 10.0
Maximum weight category: 200.0

Minimum systolic blood pressure: -150
Maximum systolic blood pressure: 16020

Minimum diastolic blood pressure: -70
Maximum diastolic blood pressure: 11000

Minimum cholesterol category: 1
Maximum cholesterol category: 3

Minimum glucose category: 1
Maximum glucose category: 3

Minimum smoke category: 0
Maximum smoke category: 1

Minimum alcohol category: 0
Maxmimum alcohol category: 1

Minimum active category: 0
Maximum active category: 1

Minimum cardio catgory: 0
Maximum cardio category: 1

In [9]:
#Height range of both genders were taken to 2SD from global mean and drop heights outside of this range
cardio_clean = cardio_clean[(cardio_clean['height']>150) & (cardio_clean['height']<195)]

#Checking new range of 'height'
print("New minimum height in cm:", cardio_clean['height'].min())
print("New maximum height in cm:", cardio_clean['height'].max())
print("Number of rows dropped due to height anomalies:", 70000-len(cardio_clean['height']))

New minimum height in cm: 151
New maximum height in cm: 194
Number of rows dropped due to height anomalies: 2621

In [10]:
#Weight range of both genders were taken considering the mean global distribution and drop weights outside of this range
cardio_clean = cardio_clean[(cardio_clean['weight']>39) & (cardio_clean['weight']<151)]

#Checking new range of 'weight'
print("New minimum weight in kg:", cardio_clean['weight'].min())
print("New maximum weight in kg:", cardio_clean['weight'].max())
print("Number of rows dropped due to weight anomalies:", 70000-len(cardio_clean['weight']))

New minimum weight in kg: 40.0
New maximum weight in kg: 150.0
Number of rows dropped due to weight anomalies: 2700

In [11]:
#Range of systolic bp chosen based on healthy and unhealthy ranges
cardio_clean = cardio_clean[(cardio_clean['bp_systolic']>89) & (cardio_clean['bp_systolic']<201)]

#Checking if there's any irregularities in 'bp_systolic'
print("New minimum systolic bp:", cardio_clean['bp_systolic'].min())
print("New maximum systolic bp:", cardio_clean['bp_systolic'].max())
print("Number of rows dropped due to systolic bp anomalies:", 70000-len(cardio_clean['bp_systolic']))

New minimum systolic bp: 90
New maximum systolic bp: 200
Number of rows dropped due to systolic bp anomalies: 3102

In [12]:
#Range of diastolic bp chosen based on healthy and unhealthy ranges
cardio_clean = cardio_clean[(cardio_clean['bp_diastolic']>54) & (cardio_clean['bp_diastolic']<151)]

#Checking if there's any irregularities in 'bp_diastolic'
print("New minimum diastolic bp:", cardio_clean['bp_diastolic'].min())
print("New maximum diastolic bp:", cardio_clean['bp_diastolic'].max())
print("Number of rows dropped due to diastolic bp anomalies:", 70000-len(cardio_clean['bp_diastolic']))

New minimum diastolic bp: 55
New maximum diastolic bp: 150
Number of rows dropped due to diastolic bp anomalies: 4114

In [13]:
#Create a new column 'BMI'. Formula is weight/(height in metres)*(height in metres)
cardio_clean['bmi'] = cardio_clean['weight']/(cardio_clean['height']*cardio_clean['height']/10000)

#Print first few tables of dataset to check 
cardio_clean.head()

,id,age,gender,height,weight,bp_systolic,bp_diastolic,cholesterol,gluc,smoke,alco,active,cardio,bmi
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,21.967120
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,34.927679
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,23.507805
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,28.710479
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,23.011177

In [14]:
#Round off values in 'bmi' to 2dp
cardio_clean['bmi'] = cardio_clean['bmi'].round(2)

#Print the Variable Information to check number of dp is correct
cardio_clean.head()

,id,age,gender,height,weight,bp_systolic,bp_diastolic,cholesterol,gluc,smoke,alco,active,cardio,bmi
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,21.97
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,34.93
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,23.51
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,28.71
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,23.01

In [15]:
#Create a new column in the dataframe 'age_years' to convert the age of patients from days into years for easier reading
cardio_clean['age_years'] = cardio_clean['age']/365

#Convert Variable 'age_years' from float to integer data type
cardio_clean['age_years'] = cardio_clean['age_years'].astype('int64')

#Print the Variable Information to check data type has been converted
cardio_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 65886 entries, 0 to 69999
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            65886 non-null  int64
 1   age           65886 non-null  int64
 2   gender        65886 non-null  int64
 3   height        65886 non-null  int64
 4   weight        65886 non-null  float64
 5   bp_systolic   65886 non-null  int64
 6   bp_diastolic  65886 non-null  int64
 7   cholesterol   65886 non-null  int64
 8   gluc          65886 non-null  int64
 9   smoke         65886 non-null  int64
 10  alco          65886 non-null  int64
 11  active        65886 non-null  int64
 12  cardio        65886 non-null  int64
 13  bmi           65886 non-null  float64
 14  age_years     65886 non-null  int64
dtypes: float64(2), int64(13)
memory usage: 8.0 MB

In [16]:
#Checking if there's any irregularities in 'gender'
age_min = cardio_clean['age_years'].min()
age_max = cardio_clean['age_years'].max()

print("Age min:", age_min)
print("Age max:", age_max)

Age min: 29
Age max: 64

In [17]:
#Choosing which number will separate the different age categories
bins = [25,35,45,55,65]

#Choosing name of different categories
labels = ['25-34', '35-44', '45-54', '55-64']

#Group different ages into discrete bins to create different age ranges, converting numerical data to categories
cardio_clean['age_cat'] = pd.cut(cardio_clean['age_years'], bins=bins, labels=labels)

#Check the existence of new column 'age_cat'
cardio_clean.head()

,id,age,gender,height,weight,bp_systolic,bp_diastolic,cholesterol,gluc,smoke,alco,active,cardio,bmi,age_years,age_cat
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,21.97,50,45-54
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,34.93,55,45-54
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,23.51,51,45-54
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,28.71,48,45-54
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,23.01,47,45-54

In [18]:
#Import new library
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

#Label Encoding to turn each category in 'age_cat' into unique integers
cardio_clean['age_cat_int'] = le.fit_transform(cardio_clean['age_cat'])

#Checking if there's any irregularities in 'cardio'
print("Minimum age_cat_int category:", cardio_clean['age_cat_int'].min())
print("Maximum age_cat_ category:", cardio_clean['age_cat_int'].max())

Minimum age_cat_int category: 0
Maximum age_cat_ category: 3

In [19]:
#Renumber index due to inconsecutive index numbers as some rows were dropped
cardio_clean = cardio_clean.reset_index(drop=True)

#Reassign the values of 'id' to match index as some rows were dropped 
cardio_clean['id'] = range(len(cardio_clean))

#Check that index matches with 'id'
cardio_clean[-1:]

,id,age,gender,height,weight,bp_systolic,bp_diastolic,cholesterol,gluc,smoke,alco,active,cardio,bmi,age_years,age_cat,age_cat_int
65885,65885,20540,1,170,72.0,120,80,2,1,0,0,1,0,24.91,56,55-64,3

In [20]:
#Final check to make sure the number of rows for each column tally
cardio_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65886 entries, 0 to 65885
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            65886 non-null  int64
 1   age           65886 non-null  int64
 2   gender        65886 non-null  int64
 3   height        65886 non-null  int64
 4   weight        65886 non-null  float64
 5   bp_systolic   65886 non-null  int64
 6   bp_diastolic  65886 non-null  int64
 7   cholesterol   65886 non-null  int64
 8   gluc          65886 non-null  int64
 9   smoke         65886 non-null  int64
 10  alco          65886 non-null  int64
 11  active        65886 non-null  int64
 12  cardio        65886 non-null  int64
 13  bmi           65886 non-null  float64
 14  age_years     65886 non-null  int64
 15  age_cat       65886 non-null  category
 16  age_cat_int   65886 non-null  int32
dtypes: category(1), float64(2), int32(1), int64(13)
memory usage: 7.9 MB

In [21]:
cardio_clean.to_csv('cardio_clean.csv', index=False)

# ipywidgets

In [31]:
#Import package ipywidgets
import ipywidgets as widgets
from IPython.display import display

In [42]:
age_checkbox = widgets.Checkbox(value=False, description='Age', disabled=False)
age_input = widgets.IntSlider(value=40, min=1, max=100, disabled=True)
def toggle_age_input(change):
    age_input.disabled = not change.new

age_checkbox.observe(toggle_age_input, names='value')

display(age_checkbox, age_input)
#gender_checkbox = widgets.Checkbox(value=False, description='Gender')
#weight_checkbox = widgets.Checkbox(value=False, description='Weight')
#height_checkbox = widgets.Checkbox(value=False, description='Height')
#smoke_checkbox = widgets.Checkbox(value=False, description='Smoke')
#alcohol_checkbox = widgets.Checkbox(value=False, description='Alcohol')
#active_checkbox = widgets.Checkbox(value=False, description='Exercise')

Checkbox(value=False, description='Age')

IntSlider(value=40, disabled=True, min=1)

In [61]:
#Define non-clinical attributes and their labels

import ipywidgets as widgets
from IPython.display import display

# 1. List ALL your features here (Age, Weight, etc.)
features = ['Age', 'Weight']
all_widgets = {}
rows = []

for f in features:
    # Create the Switch (Checkbox)
    chk = widgets.Checkbox(description=f"Enable {f}", value=False)
    
    # Create the Slider (Disabled by default)
    sld = widgets.IntSlider(description=f"{f}:", disabled=True, value=50)
    
    # LINK: This makes the slider move ONLY when checked
    widgets.dlink((chk, 'value'), (sld, 'disabled'), transform=lambda x: not x)
    
    # Store for later
    all_widgets[f] = {'check': chk, 'slider': sld}
    rows.append(widgets.HBox([chk, sld]))

# 2. THE MACHINE INTERFACE: A button to "Submit" the values
predict_btn = widgets.Button(description="Run Prediction", button_style='success')

def on_predict(b):
    print("--- Machine Input Received ---")
    for f in features:
        if all_widgets[f]['check'].value:
            print(f"{f}: {all_widgets[f]['slider'].value}")
        else:
            print(f"{f}: [NOT ENABLED - Using Default]")

predict_btn.on_click(on_predict)

# 3. RENDER EVERYTHING
display(widgets.VBox(rows + [predict_btn]))

VBox(children=(HBox(children=(Checkbox(value=False, description='Enable Age'), IntSlider(value=50, description…