In [2]:
#Import basic libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
sb.set()

In [5]:
#Import Cardio dataset
cardio = pd.read_csv('cardio_train.csv', sep=';')
#Read first few rows of dataset
cardio.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [21]:
#Find out more information about dataset
cardio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [22]:
#Create a copy of the dataset
cardio_clean = cardio.copy()

#Convert all variable name to UPPERCASE
cardio_clean.columns = cardio_clean.columns.str.upper()

# Print the Variable Information to check
cardio_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           70000 non-null  int64
 1   AGE          70000 non-null  int64
 2   GENDER       70000 non-null  int64
 3   HEIGHT       70000 non-null  int64
 4   WEIGHT       70000 non-null  float64
 5   AP_HI        70000 non-null  int64
 6   AP_LO        70000 non-null  int64
 7   CHOLESTEROL  70000 non-null  int64
 8   GLUC         70000 non-null  int64
 9   SMOKE        70000 non-null  int64
 10  ALCO         70000 non-null  int64
 11  ACTIVE       70000 non-null  int64
 12  CARDIO       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [23]:
dupid_data_clean = cardio_clean[cardio_clean.duplicated("ID", keep = False)]
print("Titles with Duplicate IDs :", len(dupid_data_clean))
cardio_clean.isnull().sum()

Titles with Duplicate IDs : 0

ID             0
AGE            0
GENDER         0
HEIGHT         0
WEIGHT         0
AP_HI          0
AP_LO          0
CHOLESTEROL    0
GLUC           0
SMOKE          0
ALCO           0
ACTIVE         0
CARDIO         0
dtype: int64

In [24]:
#Differentiate whether a varible is a numerical or categorical data type
cardio_clean['GENDER'] = cardio_clean['GENDER'].astype('category')
cardio_clean['CHOLESTEROL'] = cardio_clean['CHOLESTEROL'].astype('category')
cardio_clean['GLUC'] = cardio_clean['GLUC'].astype('category')
cardio_clean['SMOKE'] = cardio_clean['SMOKE'].astype('category')
cardio_clean['ALCO'] = cardio_clean['ALCO'].astype('category')
cardio_clean['ACTIVE'] = cardio_clean['ACTIVE'].astype('category')
cardio_clean['CARDIO'] = cardio_clean['CARDIO'].astype('category')

#Print the Variable Information to check
cardio_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           70000 non-null  int64
 1   AGE          70000 non-null  int64
 2   GENDER       70000 non-null  category
 3   HEIGHT       70000 non-null  int64
 4   WEIGHT       70000 non-null  float64
 5   AP_HI        70000 non-null  int64
 6   AP_LO        70000 non-null  int64
 7   CHOLESTEROL  70000 non-null  category
 8   GLUC         70000 non-null  category
 9   SMOKE        70000 non-null  category
 10  ALCO         70000 non-null  category
 11  ACTIVE       70000 non-null  category
 12  CARDIO       70000 non-null  category
dtypes: category(7), float64(1), int64(5)
memory usage: 3.7 MB

In [38]:
#Create a new column in the dataframe 'AGE_YEARS' to convert the age of patients from days into years for easier reading
cardio_clean['AGE_YEARS'] = cardio_clean['AGE']/365

#Convert Variable 'AGE_YEARS' from float to integer data type
cardio_clean['AGE_YEARS'] = cardio_clean['AGE_YEARS'].astype('int64')

#Print the Variable Information to check
cardio_clean.head()

,ID,AGE,GENDER,HEIGHT,WEIGHT,AP_HI,AP_LO,CHOLESTEROL,GLUC,SMOKE,ALCO,ACTIVE,CARDIO,AGE_YEARS
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0,50
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1,55
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1,51
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1,48
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0,47